### ISSUE TITLE
Scoring On Answers 🌶 

### ISSUE THREAD

**Issue by samgo1** [samgo1/Soen341#17]
_The answers table in the database needs a new column called 'votes' of type integer._
[Story points: 8]
Answers need a scoring attribute so we can do the following : 

**Backend**
 - [x] Sort the answers by score method SP: 3 (Arnaud/Seb)
- [x] Reject an answer method SP: 3 (Arnaud/Seb)

**Frontend**
 - [x] button to the left of the answer to upvote it SP: 2 (Jeffrey)

                                       
                          Should be done by Wednesday 28th of February

**Comment by jeffreytang97** [comment]
I'm on it!

**Comment by sebdesl** [comment]
We can now reject answers if they have downvotes equal to 0.6 * total votes. Also the answers are sorted based on weighted_scores in decreasing order. +1 for upvotes/-1 for downvotes
