### ISSUE TITLE
Installing BootStrap on the app

### ISSUE THREAD

**Issue by samgo1** [samgo1/Soen341#27]
SP : 2

We need to install bootstrap on the app to work on our front-end.
Documentation of bootstrap https://getbootstrap.com/docs/4.0/getting-started/introduction/#starter-template

**Comment by Khal-Shah** [comment]
Changes:
        modified:   Gemfile
        modified:   Gemfile.lock
        modified:   app/.DS_Store
        modified:   app/assets/javascripts/application.js
        modified:   app/assets/stylesheets/application.css

Gems include: 
bootstrap-sass
jquery
simple_form
