### ISSUE TITLE
Edit question page front-end design

### ISSUE THREAD

**Issue by jeffreytang97** [samgo1/Soen341#31]
Story points: 7

**Comment by jeffreytang97** [comment]
Practically the same ass the creation page

**Comment by ThierrySt-Arnaud** [comment]
The edit and creation views can be done in a single file that will then be rendered from both the creation and editing views. Take a look at point 5.12 in the Rails Getting Started.

**Comment by jeffreytang97** [comment]
ah ok I will take a look. Thanks!
