### ISSUE TITLE
Create a home page welcoming new users

### ISSUE THREAD

**Issue by FYK96** [samgo1/Soen341#36]
SP: 6 (sam: 2 ,Nick: 4)
This page should include the following:

- [ ] about section - detailing the web app's information and purpose

- [ ] sign in or sign up button (control panel)

- [ ] Questions button - that directs users to questions page.

- [ ] add sign up sheet next to about section

**Comment by samgo1** [comment]
This is what I have so far at the root of our website.

![screen shot 2018-02-08 at 11 37 46 pm](https://user-images.githubusercontent.com/21287072/36011977-1ae425c0-0d29-11e8-939c-fa0c4e07cabd.png)

**Comment by nickzombolas** [comment]
I have added the backend functionality for user sign up on this page.

**Comment by nickzombolas** [comment]
I believe Sam did the front end for this page and I did the backend. Is there more work than needs to be done on this issue or can it be closed?
