### ISSUE TITLE
Add delete question functionality in the "list all questions" web page

### ISSUE THREAD

**Issue by AvkashSharma** [samgo1/Soen341#44]
SP:1
User should have the ability to delete the question from the "list all questions" page.

**Comment by AvkashSharma** [comment]
Added Delete 
<img width="1156" alt="screen shot 2018-02-09 at 2 13 03 am" src="https://user-images.githubusercontent.com/33563851/36015975-e47d4852-0d3e-11e8-9044-7a3115f0b08f.png">
feature:

**Comment by samgo1** [comment]
very pretty 😄

**Comment by AvkashSharma** [comment]
Changes made in the app-> view->articles-> index.html.erb
Code snippet added:
`<%= link_to "Delete this question", question_path(question), method: :delete,
																   data: {confirm: "Are you sure you want to delete the article?"},
																   class: "btn btn-xs btn-danger" %>`
