### ISSUE TITLE
Make changes to font size of the Question title and description on the list all questions page

### ISSUE THREAD

**Issue by AvkashSharma** [samgo1/Soen341#53]
SP: 1
The font size of the question title and description is same. Needs to be modified so that question title appears different from the body of the question description. 

<img width="936" alt="screen shot 2018-02-09 at 7 20 05 pm" src="https://user-images.githubusercontent.com/33563851/36055960-498a3964-0dce-11e8-82c4-1defbb81d7dc.png">

**Comment by AvkashSharma** [comment]
Made changes. 

Preview of the page
<img width="1258" alt="screen shot 2018-02-09 at 9 03 57 pm" src="https://user-images.githubusercontent.com/33563851/36057507-fc12518a-0ddc-11e8-9110-800af95079fa.png">

**Comment by jeffreytang97** [comment]
Are you sure it is a good idea to put edit question and delete question at the main page? Because all the forum pages they don't have it like this and also I did put an edit option but took it out.

**Comment by AvkashSharma** [comment]
The options were there from before. I just changed the view to make it look appealing.

**Comment by AvkashSharma** [comment]
Team has decided to remove the Edit and Delete options from the List all questions page
