### ISSUE TITLE
Establishing CSS Workflow & Entire Site Formatting 🎨 

### ISSUE THREAD

**Issue by samgo1** [samgo1/Soen341#95]
SP:5
- [x] Establishing a workflow that everyone can follow for keeping structured CSS _&_ explaining it to the others at the next meeting
- [x] Cleaning up the views containing html <head>, <body> tags and anything else that overwrites a previously executed stylesheet

                                   Should be done by Wednesday 28th of February

**Comment by samgo1** [comment]
@ThierrySt-Arnaud Can you talk about the css workflow tomorrow at the meeting?

**Comment by ThierrySt-Arnaud** [comment]
Yes, I wanted to do that!

Le mer. 7 mars 2018 à 22:36, Samuel Gosselin <notifications@github.com> a
écrit :
